permalink: /:title.html
title: Evonna Wu
description: "Evonna Wu's Blog"
keywords: programming, data, machine learning, alexandre martins, al3xandr3
production_url: http://al3xandr3.github.io
pygments: false
markdown: kramdown
author :
  name : Alexandre Matos Martins
  github : al3xandr3
  twitter : al3xandr3
  email: al3xandr3@gmail.com
  linkedin: al3xandr3
disqus_shortname: al3xandr3
analytics: UA-39542235-1
