paginate: 1
markdown: rdiscount
highlighter: pygments
permalink: /blog/:title
rdiscount:
  extensions: [smart]
name: Evonna Wu
description: The personal blog of a data scientist/ yogi , NYC
url: http://yvonnengnyc.github.io/
