permalink: /:title.html
title: Evonna Wu
description: "Evonna Wu's Blog"
keywords: programming, data, machine learning, alexandre martins, al3xandr3
production_url: http://yvoonenynyc.github.io
pygments: false
markdown: kramdown
author :
  name : Evonna Wu
  github : -
  twitter : al3xandr3
  linkedin: Cong Wu
disqus_shortname: evonnawu
analytics: UA-39542235-1
